[versions]
junit = "6.0.1"
mockito = "5.20.0"
assertj = "3.27.6"


[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }


[bundles]
junit-runtime = [ "junit-jupiter-engine", "junit-platform-launcher" ]
junit-jupiter = [ "junit-jupiter-api", "junit-jupiter-params" ]
testing = [ "mockito-core", "mockito-junit-jupiter", "assertj-core" ]
