[versions]
servlet-api = "6.1.0"
jedis = "7.1.0"
postgresql = "42.7.8"
hibernate = "7.1.11.Final"

thymeleaf = "3.1.3.RELEASE"

junit = "6.0.1"
mockito = "5.20.0"
assertj = "3.27.6"


[libraries]
servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "servlet-api" }
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
postgresql-driver = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hibernate-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate" }

thymeleaf-core = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }


[bundles]
junit-runtime = [ "junit-jupiter-engine", "junit-platform-launcher" ]
junit-jupiter = [ "junit-jupiter-api", "junit-jupiter-params" ]
testing = [ "mockito-core", "mockito-junit-jupiter", "assertj-core" ]
